name: 💡 Feature request
description: Suggest an idea or new feature for this project
title: "[IDEA]: "
labels: [enhancement]
assignees:
  - foenichs
body:
  - type: checkboxes
    attributes:
      label: Please confirm the following.
      options:
        - label: I checked the [existing issues](https://github.com/foenichs/ghastling/issues) for duplicate suggestions
          required: true
        - label: I have ensured that my idea isn't already considered in the [README](https://github.com/foenichs/ghastling/blob/main/README.md)
          required: true
  - type: textarea
    attributes:
      label: Describe your idea
      description: A detailed description of your idea and why it should be implemented. You can also include screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the suggested enhancement here.
    validations:
      required: false
